---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-exercise
  labels:
    app: postgres
    env: dev
    purpose: demo
spec:
  containers:
    - name: postgres-demo
      image: postgres:16 #latest
      env:
        - name: POSTGRES_DB
          value: nop
        - name: POSTGRES_USER
          value: ltdevops
        - name: POSTGRES_PASSWORD
          value: admin123
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
