--- 
apiVersion: batch/v1
kind: Job
metadata:
  name: jobdemo
spec:
  backoffLimit: 2
  template: 
    metadata:
      labels:
        app: Job
    spec: 
      restartPolicy: OnFailure
      containers: 
        - name: downloadjob
          image: alpine
          args: 
            - sleep
            - 5s




