---
pool: 
  vmImage: 'ubuntu-22.04'
variables:
  DEFAULT_BRANCH: master
trigger:
  - "$(DEFAULT_BRANCH)"
schedules: 
  - cron: '30 1 * * 6'
    displayName: weeklyBuild
    branches:
      include:
        - "$(DEFAULT_BRANCH)"
parameters:
  - name: jdkversion
    displayName: Java Version
    type: string
    default: 1.17
    values:
      - '1.17'
      - '1.11'
      - '1.10'
      - '1.9'
      - '1.8'
stages:
  - stage: build
    displayName: Maven build
    jobs:
      - job: build
        steps: 
          - task: Maven@4
            inputs: 
              mavenPOMFile: 'pom.xml'
              goals: clean package
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: "${{ parameters.jdkversion }}"
          - task: CopyFiles@2
            inputs:
              Contents: '**/*.war'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: GameOfLife




