---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fe-rs
  labels:
    env: dev
    topic: service
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fe
  template:
    metadata:
      labels:
        app: fe
        topic: pod
    spec:
      containers:
        - image: nginx
          name: fe-cont
          ports:
            - containerPort: 80
              name: fe
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 4
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /
              port: 80
