---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: web-pod
      labels:
        app: web
        env: dev
        version: v3.0
    spec:
      containers:
        - name: app
          image: shaikkhajaibrahim/dmtest:3.0
          readinessProbe:
            initialDelaySeconds: 3
            failureThreshold: 1
            httpGet:
              path: /
              port: 80
            successThreshold: 3
            periodSeconds: 5
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
