--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: invoiceservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        name: invoiceservice
        version: v1.0
    spec:
      containers:
        - name: invoiceservice
          image: kumar1502/invoiceservice:1.0
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          # ports:
          #   - containerPort: 5000
          #     name: invoiceservice
          #     protocol: TCP
        #  resources:
        #     limits:
        #       cpu: 250m
        #       memory: 256Mi 
      restartPolicy: Always
