--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loglserver-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: loglserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: loglserver 
        version: v1.0
    spec:
      containers:
        - name: loglserver
          image: datalust/seq:latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 80
              name: loglserver
              protocol: TCP
        #  resources:
        #     limits:
        #       cpu: 250m
        #       memory: 256Mi 
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: loglserver
spec:
  selector:
    name: loglserver
  ports:
    - name: test
      port: 5341
      targetPort: 80
      protocol: TCP
