--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagementapi-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: vehiclemanagementapi  
  template:
    metadata:
      labels: 
        version: v1.0
        name: vehiclemanagementapi
    spec:
      containers:
        - name: vehiclemanagementapi
          image: kumar1502/vehiclemanagementapi:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          ports:
            - containerPort: 5000
              name: vehicle-1
              protocol: TCP
        #  resources:
        #     limits:
        #       cpu: 250m
        #       memory: 256Mi 
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagementapi
spec: 
  selector:
    name: vehiclemanagementapi
  ports:
    - name: test
      port: 5000
      targetPort: 5000
      protocol: TCP
