--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: webapp 
        version: v1.0
    spec:
      containers:
        - name: webapp
          image: kumar1502/webapp:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          ports:
            - containerPort: 7005
              name: workshop
              protocol: TCP
        #  resources:
        #     limits:
        #       cpu: 250m
        #       memory: 256Mi 
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    name: webapp
  type: LoadBalancer
  ports:
    - port: 7005
      targetPort: 7005
      protocol: TCP
