--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagementeventhandler
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      name: workshopmanagementeventhandler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: workshopmanagementeventhandler 
        version: v1.0
    spec:
      containers:
        - name: workshophandler
          image: kumar1502/workshopmanagementeventhandler:1.0
          env: 
            - name: DOTNET_ENVIRONMENT
              value: Production
          # ports:
          #   - containerPort: 5000
          #     name: workshopmanagementeventhandler
          #     protocol: TCP
        #  resources:
        #     limits:
        #       cpu: 250m
        #       memory: 256Mi 
      restartPolicy: Always
