--- 
- name: install nopCommerce project on ubuntu
  hosts: all
  become: yes
  vars:
    nopCommerce_url: "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.4/nopCommerce_4.70.4_NoSource_linux_x64.zip"
    nop_home_dir: /var/www/nopCommerce
  tasks:
    - name: Install unzip, dotnet and nginx
      ansible.builtin.apt:
        name: "{{ item.name }}"
        update_cache: yes
        state: present
      loop:
        - {name: unzip }
        - {name: dotnet-sdk-8.0 }
        - {name: nginx}
    - name: update ASP.NET configuration
      ansible.builtin.copy:
        src: default
        dest: /etc/nginx/sites-available/default
        remote_src: no
    - name: Create nopCommerce Directory
      ansible.builtin.file:
        path: "{{ nop_home_dir }}"
        state: directory
    - name: find stats of nopCommerce folder
      ansible.builtin.stat:
        path: "{{ nop_home_dir }}/App_Data"
      register: nopCommerce_appdata_folder_stats
    # - name: print stats
    #   debug:
    #     var: nopCommerce_appdata_folder_stats.stat.exists
    - name: Install nopCommerce website
      ansible.builtin.unarchive:
        src: "{{ nopCommerce_url }}"
        dest: "{{ nop_home_dir }}"
        remote_src: yes
      when: nopCommerce_appdata_folder_stats.stat.exists == false
    - name: Create bin and logs Directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop:
        - {path: /var/www/nopCommerce/bin}
        - {path: /var/www/nopCommerce/logs}
      notify:
        - change group permissions
        - change ownership permissions
    - name: update nopCommerce service file
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
      notify:
        - Start nopCommerce service
        - restart nginx
  handlers:
    - name: restart nginx 
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
    - name: Start nopCommerce service
      ansible.builtin.systemd_service:
        name: nopCommerce.service
        enabled: true 
        state: started
    - name: change group permissions
      ansible.builtin.shell:
        cmd: "chgrp -R www-data {{ nop_home_dir }}"
        executable: "/bin/bash"
    - name: change ownership permissions
      ansible.builtin.shell:
        cmd: "chown -R www-data {{ nop_home_dir }}"
        executable: "/bin/bash"
