--- 
- name: install nopCommerce project on ubuntu
  hosts: localhost
  become: yes
  vars:
    dotnet_version: dotnet-sdk-8.0
    nopCommerce_url: "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.4/nopCommerce_4.70.4_NoSource_linux_x64.zip"
    nop_home_dir: /var/www/nopCommerce
  tasks:
    - name: update packages and install unzip
      ansible.builtin.apt:
        name: unzip
        update_cache: yes
        state: present
    - name: Install dotnet
      ansible.builtin.apt:
        name: "{{ dotnet_version }}"
        state: present
    - name: install nginx 
      ansible.builtin.apt: 
        name: nginx
        state: present
    - name: update ASP.NET configuration
      ansible.builtin.copy:
        src: default
        dest: /etc/nginx/sites-available/default
        remote_src: no
    - name: Create nopCommerce Directory
      ansible.builtin.file:
        path: "{{ nop_home_dir }}"
        state: directory
    # - name: Navigate go to the nopCommerce folder
    #   shell: cd "{{ nop_home_dir }}"
    - name: find stats of nopCommerce folder
      ansible.builtin.stat:
        path: "{{ nop_home_dir }}"
      register: nopCommerce_folder_stats
    - name: print stats
      debug:
        var: nopCommerce_folder_stats.stat.exists
    - name: Install nopCommerce website
      ansible.builtin.unarchive:
        src: "{{ nopCommerce_url }}"
        dest: "{{ nop_home_dir }}"
        remote_src: yes
      when: nopCommerce_folder_stats.stat.exists == false
    - name: Create bin and logs Directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop:
        - {path: /var/www/nopCommerce/bin}
        - {path: /var/www/nopCommerce/logs}
      notify:
        - change group permissions
        - change ownership permissions
    - name: update nopCommerce service file
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
    - name: Start nopCommerce service
      ansible.builtin.systemd_service:
        name: nopCommerce.service
        enabled: true 
        state: started
      notify:
        - restart nginx
  handlers:
    - name: restart nginx 
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
    - name: change group permissions
      ansible.builtin.shell:
        cmd: "chgrp -R www-data {{ nop_home_dir }}"
        executable: "/bin/bash"
    - name: change ownership permissions
      ansible.builtin.shell:
        cmd: "chown -R www-data {{ nop_home_dir }}"
        executable: "/bin/bash"
