---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
spec:
  containers:
    - name: nopdb
      image: mongo:8.0.0-rc8-nanoserver
      env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin123
        - name: MONGO_INITDB_DATABASE
          value: nop
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ltdevops
      resources:
        limits:
          memory: 512Mi
          cpu: 1000m
      volumeMounts:
        - name: nop-vol
          mountPath: /var/lib/mongodb
  volumes:
    - name: nop-vol
      persistentVolumeClaim:
        claimName: nop-pvc
