--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: logs
              mountPath: /var/logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes: [ "ReadWriteOnce" ] 
        storageClassName: managed-premium
        resources:
          requests:
            storage: 1Gi




    


