---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-lb
  labels:
    app: spc
    topic: svc-aks
spec:
  minReadySeconds: 25
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
    spec:
      containers:
        - image: kumar1502/spcjune2024:170624
          name: spc
          ports:
            - containerPort: 8080
              #protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 350Mi

---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
