---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    app: spc-replpica
    env: dev
    topic: replicasets
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
        topic: replica
    spec:
      containers:
        - name: spc
          image: springcommunity/spring-framework-petclinic
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
