---
apiVersion: v1
kind: Pod
metadata:
  name: postgressql-pod
  labels:
    app: db
spec:
  containers:
    - name: nopdb
      image: postgres:14.12-alpine
      env:
        - name: POSTGRES_DB
          value: nop
        - name: POSTGRES_USER
          value: ltdevops
        - name: POSTGRES_PASSWORD
          value: admin123
      resources:
        limits:
          memory: 512Mi
          cpu: 1000m
      volumeMounts:
        - name: nop-vol
          mountPath: /var/lib/postgressql
  volumes:
    - name: nop-vol
      persistentVolumeClaim:
        claimName: nop-pvc
